name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */3 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
  
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        env: 
        user.email: ${{ secrets.user.email }} # secrets_id 提
        run: |
          git config --local user.email "$user.email"
          git config --local user.name "mopburn"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
